export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHANGE_LIST = 'CHANGE_LIST'
export const MOUSE_ENTER = 'MOUSE_ENTER'
export const MOUSE_LEAVE = 'MOUSE_LEAVE'
export const CHANGE_PAGE = 'CHANGE_PAGE'